

# Comparison between List and NumPy
-----------------------------------
List is slow and numpy is fast. 

One reason is that numpy uses fixed types and list does not. 
Benefit: Because numpy has less bytes of memory so it is faster to read less bytes of memory

Second reason is that numpy has contiguous memory and list has chunks of bytes that are being allocated without sequentially. 
Benefit: It use SIMD Vector processing and has effective cache utilization

In list we do insertion, deletion, appending, concatenation. But numppy has much more to it as well.

Numpy can be used for Mathemattics, Plotting, Backend(store images) and Machine Learning stuff.
 

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
#2D array
b = np.array([[9.0, 7.0, 8.0], [4.0, 3.0, 9.5]]) #double square bracket is must
print(b)

[[9.  7.  8. ]
 [4.  3.  9.5]]


In [4]:
b.ndim #to get dimension

2

In [5]:
b.shape

(2, 3)

In [6]:
b.dtype

dtype('float64')

In [7]:
b.itemsize #to get size
#the output is 8 because the type is float

8

In [8]:
b.nbytes #to get the total size
#8*no of items

48

In [9]:
a = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]]) 
print(a)

[[1 2 3 4 5 6 7 8 9]
 [9 8 7 6 5 4 3 2 1]]


In [11]:
#to get a specific element
a[1,3] #[row starts from 0, column starts from 0]

6

In [12]:
a[0, :] #[first row, all columns]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[: , 0] #[all rows, first column]

array([1, 9])

In [14]:
a[0, 0: 8 :2] #[row, startindex : endindex : stepsize]

array([1, 3, 5, 7])

In [15]:
a[1,5] = 30 #changes element
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [ 9  8  7  6  5 30  3  2  1]]
