# **Advanced NumPy** 
Link: https://www.youtube.com/watch?v=cYugp9IN1-Q 

In [ ]:
import numpy as np

In [ ]:
gene0 = [100, 200, 50, 400]
gene1 = [50, 0, 0, 100]
gene2 = [350, 100, 50, 200]
expression_data = [gene0, gene1, gene2]

In [ ]:
a = np.array(expression_data)
print(a)

[[100 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]]


In [ ]:
def print_info(a):
    print('number of elements:', a.size)
    print('number of dimensions:', a.ndim)
    print('shape:', a.shape)
    print('data type:', a.dtype)
    print('strides:', a.strides)
    print('flags:')
    print(a.flags)
    
print_info(a) #We are using the class becuase we will be calling the info of multiple arrays again and again.

number of elements: 12
number of dimensions: 2
shape: (3, 4)
data type: int64
strides: (32, 8)
flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
print(a.data)

In [ ]:
a.ravel().shape #This creates a flattened version of the 'a' array and returns its shape as a tuple

# Here the flattened array has a shape of (n,) becuase the original array is n-dimensional

(12,)

In [ ]:
abytes = a.ravel().view(dtype=np.uint8) #This converts each element of the flattened array to an 8-bit integer and stores it in the new abytes array. 

In [ ]:
print_info(abytes)

number of elements: 96
number of dimensions: 1
shape: (96,)
data type: uint8
strides: (1,)
flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
print(abytes[:24]) #prints the first 24 elements of the NumPy array abytes.

[100   0   0   0   0   0   0   0 200   0   0   0   0   0   0   0  50   0
   0   0   0   0   0   0]


In [ ]:
abytes[1] = 1# changes the value of first element to 1.
print(abytes[:24])

[100   1   0   0   0   0   0   0 200   0   0   0   0   0   0   0  50   0
   0   0   0   0   0   0]


In [ ]:
a.ravel()[0]

356

### Transpose of a


In [ ]:
print_info(a)

number of elements: 12
number of dimensions: 2
shape: (3, 4)
data type: int64
strides: (32, 8)
flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
print_info(a.T) #shape of matrix will be changed

number of elements: 12
number of dimensions: 2
shape: (4, 3)
data type: int64
strides: (8, 32)
flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



### **Advanced operations: axis-wise evaluation**

In [40]:
expr = np.load('expr.npy')

In [41]:
print_info(expr)

number of elements: 7687500
number of dimensions: 2
shape: (20500, 375)
data type: uint32
strides: (4, 82000)
flags:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [42]:
total = np.sum(expr)

In [43]:
lib_size = np.sum(expr, axis=0)

In [44]:
lib_size.shape


(375,)

### **Advanced operations: broadcasting**

In [47]:
a

array([[356, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [48]:
a + 5  # simplest broadcasting

array([[361, 205,  55, 405],
       [ 55,   5,   5, 105],
       [355, 105,  55, 205]])

In [49]:
b = np.array([1, 2, 3, 4])
a + b  # broadcasting

array([[357, 202,  53, 404],
       [ 51,   2,   3, 104],
       [351, 102,  53, 204]])

In [52]:
b = np.array([1, 2, 3])
a + b 

ValueError: ignored

In [53]:
b = np.array([[1], [2], [3]])
a + b  #shape compatibility

array([[357, 201,  51, 401],
       [ 52,   2,   2, 102],
       [353, 103,  53, 203]])

In [54]:
b.shape

(3, 1)

In [56]:
lib_size = np.sum(expr, axis=0)

In [57]:
print(expr.shape)
print(lib_size.shape)
print(lib_size[np.newaxis, :].shape)

(20500, 375)
(375,)
(1, 375)


In [58]:
np.all([True, True, False])

False

In [ ]:
np.all([True, True, True])

### **Linear algebra with NumPy**

In [59]:
M = np.array([[0, 1],
              [1, 1],
              [1, 0]])
v = np.array([9, 2])

print(M @ v)

[ 2 11  9]


In [60]:
print(M.T @ M)

[[2 1]
 [1 2]]


Consider the rotation matrix




*   [  cos(theta)    -sin(theta)    0]
*   [  sin(theta)    cos(theta)    0]
*   [  0    0    1]







In [61]:
theta_deg = 45
theta = np.deg2rad(theta_deg)

c = np.cos(theta)
s = np.sin(theta)

R = np.array([[c, -s, 0],
              [s,  c, 0],
              [0,  0, 1]]) 

In [62]:
x_axis = np.array([1, 0, 0]) 

In [63]:
R @ x_axis


array([0.70710678, 0.70710678, 0.        ])

In [64]:
rotated = R @ x_axis
R @ rotated

array([1.79380389e-16, 1.00000000e+00, 0.00000000e+00])